src/main/java/com/polytech/j2ee_project/model/File.java
package com.polytech.j2ee_project.model;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import org.primefaces.model.TreeNode;


@Entity
@Table(name="file")
public class File implements Serializable,FileManagerElement {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id")
    private Long id;
    
    @Column(name="file")
    private String name;
    @Column(name="date_inserted")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date insertDate;
    @Column(name="date_updated")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date updateDate;
    @Column(name="date_file")
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date fileDate;
    @Column(name="remark")
    private String remark;
    @Column(name="file_type")
    private String type;
    @Column(name="file_size")
    private long size;
    @Column(name="file_original_name")
    private String originalFilename;
    @Column(name="path")
    private String path;
    
    
    @ManyToOne
    @JoinColumn(name = "fk_folder_file", referencedColumnName = "id_folder")
    private Folder folder;
    
    @Transient
    private final static DecimalFormat format = new DecimalFormat("#0.00");
            
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getInsertDate() {
        return insertDate;
    }

    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public Date getFileDate() {
        return fileDate;
    }

    public void setFileDate(Date fileDate) {
        this.fileDate = fileDate;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public long getSize() {
        return size;
    }

    public void setSize(long size) {
        this.size = size;
    }

    public String getOriginalFilename() {
        return originalFilename;
    }

    public void setOriginalFilename(String originalFilename) {
        this.originalFilename = originalFilename;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Folder getFolder() {
        return folder;
    }

    public void setFolder(Folder folder) {
        this.folder = folder;
    }
    
    @PrePersist
    private void automaticDateInsert(){
        Date date = new Date();
        if(this.getId() == null){
            this.setInsertDate(date);
        }
        this.setUpdateDate(date);
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof File)) {
            return false;
        }
        File other = (File) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }
    @Override
    public String toString(){
        return getName();
    }

    @Override
    public String getIconPath() {
        return "images/file.png";
     }

    @Override
    public String getElementName() {
       return getName();
    }

    @Override
    public String getElementSize() {
        return String.valueOf(format.format(getSize()/1000000.)) + " Mo";
    }
    
    
}

src/main/java/com/polytech/j2ee_project/model/FileManagerElement.java
package com.polytech.j2ee_project.model;

import org.primefaces.model.TreeNode;

/**
 *
 * @author Romain
 */
public interface FileManagerElement{
    public Long getId();
    public String getIconPath();
    public String getElementName();
    public String getElementSize();
}

src/main/java/com/polytech/j2ee_project/controller/FolderController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.polytech.j2ee_project.controller;


import com.polytech.j2ee_project.model.File;
import com.polytech.j2ee_project.model.FileManagerElement;
import com.polytech.j2ee_project.model.Folder;
import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.NodeSelectEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.TreeNode;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author Erdrixx
 */

@ManagedBean(name="folderController")
@SessionScoped
public class FolderController {
    
    // ATTRIBUTS
    private TreeNode root;
    private TreeNode selectedNode;
    private ArrayList<TreeNode> nodeList;
    private String newNodeName;
    private String path ="";
    private List<FileManagerElement> content;
    private List<FileManagerElement> selectedElements;
    private FileManagerElement selectedElement;
    private String absolutePath="";
    StreamedContent sContent;
    String contentType="";
    java.io.File file;
    DefaultStreamedContent download;
    String downloadName = "";
    String currentView ="Board";

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }
 
    @ManagedProperty("#{fileService}")
    private FileService fileService;
    @ManagedProperty("#{folderService}")
    private FolderService service;
    
    @PostConstruct
    public void init() {
        root = service.init(); 
        root.setExpanded(true);
        root.setSelected(true);
        content = new ArrayList<>();
        selectedElements = new ArrayList<>();
    }
    
    private static final long serialVersionUID = 1L;
    private UploadedFile resume;

  
    //This below code is for file upload with advanced mode.
    public void uploadFile(FileUploadEvent e) throws IOException{
        UploadedFile uploadedFile=e.getFile();
        String filePath = System.getProperty("user.home") + java.io.File.separator + "FileManager" +java.io.File.separator;
        if(selectedNode !=null){
            filePath = service.createPath(selectedNode)+java.io.File.separator;
        }
        if(!service.checkName(selectedNode, uploadedFile.getFileName())){
            byte[] bytes=null;
            if (null!=uploadedFile) {
                
                
                // Récupère le contenu du fichier.
                bytes = uploadedFile.getContents();
                
                // Récupère le nom du fichier.
                String filename = uploadedFile.getFileName();
                
                // Créer le chemin dans l'arborescence si ça n'est pas déjà fait.
                java.io.File dir = new java.io.File(filePath);              
                dir.mkdirs();
                
                // Créer le fichier au bon emplacement.
                BufferedOutputStream stream = new BufferedOutputStream(new FileOutputStream(new  java.io.File(filePath+filename)));
                stream.write(bytes);
                stream.close();
                fileService.addFile(uploadedFile, selectedNode);
                FacesContext.getCurrentInstance().addMessage("messages",new FacesMessage(FacesMessage.SEVERITY_INFO,"Your File (File Name "+ uploadedFile.getFileName()+ " with size "+ uploadedFile.getSize()+ ")  Uploaded Successfully", ""));
            } 
        }else{
            FacesContext.getCurrentInstance().addMessage("messages",new FacesMessage(FacesMessage.SEVERITY_WARN,"Your File (File Name "+ uploadedFile.getFileName()+ " with size "+ uploadedFile.getSize()+ ") can't be load, delete the file with the same name before", ""));
    
        }
        content.clear();
        content.addAll(((Folder)selectedNode.getData()).getChildFolders());
        content.addAll(((Folder)selectedNode.getData()).getFile());
        // Affiche un message signifiant que l'opération s'est bien déroulée.
        }
   
    /**
     * Create a new node with the selected node like parent
     */
    public void doCreate() {
        service.doCreate(selectedNode, newNodeName);
        content.clear();
        content.addAll(((Folder)selectedNode.getData()).getChildFolders());
        content.addAll(((Folder)selectedNode.getData()).getFile());
    }

    /**
     * Update name node
     */
    public void doUpdate() {
        service.doUpdate(selectedNode, newNodeName);
        path = service.createPath(selectedNode);
        content.clear();
        content.addAll(((Folder)selectedNode.getData()).getChildFolders());
        content.addAll(((Folder)selectedNode.getData()).getFile());
    }
    
    public String goBoard(){
        return "board.xhtml";
    }
    
    /**
     * Delete node selected
     */
    public void doDelete() {
        TreeNode parent = selectedNode.getParent();
        if (!((Folder)selectedNode.getData()).getName().equals("root")){
            deleteAllSubElement((Folder) selectedNode.getData());
            ((Folder)parent.getData()).getChildFolders().remove(selectedNode.getData());
            service.doDelete(selectedNode);

            selectedNode = parent;
            path = service.createPath(selectedNode);
            selectedNode.setSelected(true);
            content.clear();
            content.addAll(((Folder)selectedNode.getData()).getChildFolders());
            content.addAll(((Folder)selectedNode.getData()).getFile());
        }
        else
             FacesContext.getCurrentInstance().addMessage("messages",new FacesMessage(FacesMessage.SEVERITY_WARN,"You can't remove the root folder",""));
    
    }
    public void deleteAllSubElement(Folder f){
        List<Folder> childs = f.getChildFolders();
        for(Folder folder:childs){
            deleteAllSubElement(folder);
        }
        for(File file:f.getFile()){
            java.io.File deletePath = new java.io.File(file.getPath());
            deletePath.delete();
        }
        String path = service.createPath(f.getNode()) +java.io.File.separator;
        java.io.File deleteFolder = new java.io.File(path);
        deleteFolder.delete();
        
    }
    /**
     * Insert a file.
     * @return 
     */
    public void doCreateFile() throws IOException
    {
        if(selectedNode!= null){
            currentView = "UploadFile";
            FacesContext.getCurrentInstance().getExternalContext().redirect("addFile.xhtml");
            FacesContext.getCurrentInstance().responseComplete();
        }    
    }
    
    public void deleteElements(){
        for(FileManagerElement element:selectedElements){
            if(element instanceof Folder){
                
                selectedNode = ((Folder)element).getNode();
                doDelete();
            }
            if(element instanceof File){
                
                File f = ((File)element);
                ((Folder)selectedNode.getData()).getFile().remove(f);
                fileService.deleteFile(f);
                 content.clear();
                 content.addAll(((Folder)selectedNode.getData()).getChildFolders());
                 content.addAll(((Folder)selectedNode.getData()).getFile());
            }
        }
    }
    public void onNodeSelect(NodeSelectEvent event) {
        
        selectedNode = (event.getTreeNode());
        path = service.createPath(selectedNode);
        content.clear();
        content.addAll(((Folder)selectedNode.getData()).getChildFolders());
        content.addAll(((Folder)selectedNode.getData()).getFile());
    }
    
    public void onElementSelect(SelectEvent e){
        try {
            String redirect = onElementSelect((FileManagerElement) e.getObject());
            if(redirect != null){
                FacesContext.getCurrentInstance().getExternalContext().redirect(redirect);
                FacesContext.getCurrentInstance().responseComplete();
            }
        } catch (IOException ex) {
            Logger.getLogger(FolderController.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }
    
    public String onElementSelect(FileManagerElement element) throws FileNotFoundException{
        
        this.selectedElement = element;
        if(element instanceof Folder){
            path = service.createPath(((Folder) element).getNode());
            this.selectedNode = ((Folder) element).getNode();
            ((Folder) element).getNode().getParent().setExpanded(true);
            ((Folder) element).getNode().getParent().setSelected(false);
            ((Folder) element).getNode().setSelected(true);
            content.clear();
            content.addAll(((Folder)selectedNode.getData()).getChildFolders());
            content.addAll(((Folder)selectedNode.getData()).getFile());
        }
        
        if(element instanceof File){
            //Action for FileElement
            file = new java.io.File(service.createPath(selectedNode)+"/"+((File)element).getName());
            
            absolutePath = file.getAbsolutePath();
            contentType = FacesContext.getCurrentInstance().getExternalContext().getMimeType(absolutePath);

src/main/webapp/addFile.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
        <title>JSF PrimeFaces File Upload Example</title>
    </h:head>
    <h:outputScript name="third/jquery/jquery.min.js" />
    <ui:composition template="WEB-INF/templates/classic.xhtml">
        <ui:define name="title">Ajouter un fichier</ui:define>
        <ui:define name="main">
            <h:body>
                <h3>Ajout d'un fichier dans le dossier  <h:outputLabel value ="#{folderController.selectedNode.data}" style="color:rgb(191, 120, 120);"/></h3>
                <h:form id="fileUpoad" prependId="false" enctype="multipart/form-data">
                    <!-- File Upload with  mode="advanced". multiple files can be uploaded. upload button  -->
                    <h:outputLabel for="fileIdFile" value="Ajouter votre fichier:" />
                    <p:fileUpload id="fileIdFile"  fileUploadListener="#{folderController.uploadFile}" mode="advanced" dragDropSupport="true" multiple="false" update="messages" sizeLimit="10000000"/>
                    <p:messages id="messages" autoUpdate="true" closable="true" />
                    <p:separator/>
                    <p:commandButton value="Retour" action="#{folderController.goBoard}" icon=" ui-icon-carat-1-w" style="margin-right : 20px;"/>
                        
                </h:form>                                 
            </h:body>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/board.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      >
      <!--xmlns:shiro="http://shiro.apache.org/tags"-->
      <style>
        table a:not(.btn), .table a:not(.btn) {
            text-decoration: none;
        }
      </style>
    <ui:composition template="WEB-INF/templates/classic.xhtml">
        <ui:define name="title">Demo</ui:define>
        <ui:define name="main"> <h:outputScript name="third/jquery/jquery.min.js" />
            <h:body>
                
                <div class="row">
                    <h:form id="idTree">
                        <p:contextMenu for="tree">
                            <p:menuitem value="Delete" actionListener="#{folderController.doDelete}" update="idTree" icon="ui-icon-close"/>
                        </p:contextMenu>
                        <!-- Arborescence -->
                        <div class="col-lg-4" >
                            <div class="panel panel-primary" style="background-color:white;">
                                <div class="panel-heading">Arborescence</div>
                                <div class="panel-body" >
                                        <p:tree style ="width: 240px;border:0px;" id="tree" value="#{folderController.root}" var="node" dynamic="true" selectionMode="single" selection="#{folderController.selectedNode}">
                                            <p:ajax event="select" update=":idTree" listener="#{folderController.onNodeSelect}"/>
                                            <p:treeNode expandedIcon="ui-icon-folder-open" collapsedIcon="ui-icon-folder-collapsed">
                                                 <h:outputText value="#{node}" />
                                             </p:treeNode>
                                        </p:tree>
                                        <p:inputText value="#{folderController.newNodeName}"/><br/>
                                        <div style="margin-top: 20px;">
                                            <p:commandButton value="Ajouter" actionListener="#{folderController.doCreate}" update="idTree" icon="ui-icon-disk" style="margin-right : 20px;"/>
                                            <p:commandButton value="Renommer" actionListener="#{folderController.doUpdate}" update="idTree" icon="ui-icon-arrowrefresh-1-w" style="margin : 0px;"/>
                                        </div>
                                </div>
                             </div>
                        </div>
                        <!-- Affichage de la vue -->
                        <div class="col-lg-8">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                        <h:outputLabel value ="#{folderController.path}" style="color:white;"/>
                                        </div>
                                <div class="panel-body">
                                    
                                    <p:dataTable id="elementsTable" var="element"  value="#{folderController.content}" selection="#{folderController.selectedElements}" rowKey="#{element.name}" >
                                       

                                        <f:facet name="header">
                                            Dossier <h:outputLabel value ="#{folderController.selectedNode.data}" style="color:rgb(191, 120, 120);"/>
                                        </f:facet>
                                        <p:ajax event="rowDblselect" update=":idTree" listener="#{folderController.onElementSelect}" />
                                                <p:column style="width:40px;text-align: center;" selectionMode="multiple"/>
                                                <p:column style="width:40px;text-align: center;" headerText=" ">
                                                    <p:graphicImage style="max-width: 20px; max-height: 20px;" name="#{element.iconPath}"/><br/>
                                                </p:column>


                                                <p:column headerText="Nom" >
                                                    <h:outputText value="#{element.elementName}" />
                                                </p:column>
                                                <p:column style="width:200px;" headerText="Taille" >
                                                    <h:outputText value="#{element.elementSize}" />
                                                </p:column>
                                                <f:facet name="footer">
                                                    <p:commandButton  value="Ajouter un fichier" action="#{folderController.doCreateFile}"/>
                                                    <p:commandButton  process="elementsTable" update="idTree" icon="ui-icon-close" value="Supprimer" action="#{folderController.deleteElements()}" />
                                                     </f:facet>
                                           </p:dataTable>
                                </div>
                             </div>
                        </div>
                    </h:form>
                </div> 
                <p:messages id="messages" autoUpdate="true" closable="true" />
            </h:body>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/reader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
                    xmlns:ui="http://java.sun.com/jsf/facelets"
                    xmlns:h="http://java.sun.com/jsf/html" 
                    xmlns:p="http://primefaces.org/ui"
                    xmlns:f="http://java.sun.com/jsf/core"
                    xmlns:pe="http://primefaces.org/ui/extensions" 
    >
      <!--xmlns:shiro="http://shiro.apache.org/tags"-->
      <style>
        table a:not(.btn), .table a:not(.btn) {
            text-decoration: none;
        }
      </style>
    <ui:composition template="WEB-INF/templates/classic.xhtml" >
        <ui:define name="title">Reader File</ui:define>
        <ui:define name="main"> <h:outputScript name="third/jquery/jquery.min.js" />
            <h:body>
                
                <div class="row">
                    <h:outputLabel value="#{folderController.absolutePath}"/>
                </div> 
                <pe:documentViewer height="600" value="#{folderController.sContent}"/> 
                <h:form>                        
                    <p:commandButton value="Retour" action="#{folderController.goBoard}" icon=" ui-icon-carat-1-w" style="margin-right : 20px;"/>
                    <p:commandButton id="downloadLink" value="Télécharger" ajax="false" actionListener="#{folderController.prepDownload}" style="float : right;">
                        <p:fileDownload value="#{folderController.download}" />
                    </p:commandButton>                 
                </h:form>
                
            </h:body>
        </ui:define>
    </ui:composition>
</html>